server:
  address: "0.0.0.0:443"
  ca_cert: "ca.crt"

fec:
  raptorq:
    enabled: true
    redundancy: 0.2
  tetrys:
    enabled: true
    redundancy: 0.1

tls:
  sni: ["google.com", "cloudflare.com"]
  cipher_suites:
    - "TLS_AES_128_GCM_SHA256"
    - "TLS_CHACHA20_POLY1305_SHA256"

keepalive:
  interval: 20

logging:
  level: "info"
  verbose: false
