[package]
name = "qf-logging"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish = false

[features]
default = []
rust-tests = []

[dependencies]
crossbeam-channel = "0.5"
log = { version = "0.4", features = ["std"] }
qf-common = { path = "../qf-common" }
serde_json = "1.0"

[target.'cfg(unix)'.dev-dependencies]
libc = "0.2"
