#include "qpack.hpp"

namespace quicsand {

// Statische Tabelle gemäß RFC 9204 Appendix A
// https://datatracker.ietf.org/doc/html/rfc9204#appendix-A
const std::vector<std::pair<std::string, std::string>> QpackCodec::static_table_ = {
    // 0
    {"", ""},
    // 1
    {":authority", ""},
    // 2
    {":path", "/"},
    // 3
    {"age", "0"},
    // 4
    {"content-disposition", ""},
    // 5
    {"content-length", "0"},
    // 6
    {"cookie", ""},
    // 7
    {"date", ""},
    // 8
    {"etag", ""},
    // 9
    {"if-modified-since", ""},
    // 10
    {"if-none-match", ""},
    // 11
    {"last-modified", ""},
    // 12
    {"link", ""},
    // 13
    {"location", ""},
    // 14
    {"referer", ""},
    // 15
    {"set-cookie", ""},
    // 16
    {":method", "CONNECT"},
    // 17
    {":method", "DELETE"},
    // 18
    {":method", "GET"},
    // 19
    {":method", "HEAD"},
    // 20
    {":method", "OPTIONS"},
    // 21
    {":method", "POST"},
    // 22
    {":method", "PUT"},
    // 23
    {":scheme", "http"},
    // 24
    {":scheme", "https"},
    // 25
    {":status", "103"},
    // 26
    {":status", "200"},
    // 27
    {":status", "304"},
    // 28
    {":status", "404"},
    // 29
    {":status", "503"},
    // 30
    {"accept", "*/*"},
    // 31
    {"accept", "application/dns-message"},
    // 32
    {"accept-encoding", "gzip, deflate, br"},
    // 33
    {"accept-ranges", "bytes"},
    // 34
    {"access-control-allow-headers", "cache-control"},
    // 35
    {"access-control-allow-headers", "content-type"},
    // 36
    {"access-control-allow-origin", "*"},
    // 37
    {"cache-control", "max-age=0"},
    // 38
    {"cache-control", "max-age=2592000"},
    // 39
    {"cache-control", "max-age=604800"},
    // 40
    {"cache-control", "no-cache"},
    // 41
    {"cache-control", "no-store"},
    // 42
    {"cache-control", "public, max-age=31536000"},
    // 43
    {"content-encoding", "br"},
    // 44
    {"content-encoding", "gzip"},
    // 45
    {"content-type", "application/dns-message"},
    // 46
    {"content-type", "application/javascript"},
    // 47
    {"content-type", "application/json"},
    // 48
    {"content-type", "application/x-www-form-urlencoded"},
    // 49
    {"content-type", "image/gif"},
    // 50
    {"content-type", "image/jpeg"},
    // 51
    {"content-type", "image/png"},
    // 52
    {"content-type", "text/css"},
    // 53
    {"content-type", "text/html; charset=utf-8"},
    // 54
    {"content-type", "text/plain"},
    // 55
    {"content-type", "text/plain;charset=utf-8"},
    // 56
    {"range", "bytes=0-"},
    // 57
    {"strict-transport-security", "max-age=31536000"},
    // 58
    {"strict-transport-security", "max-age=31536000; includesubdomains"},
    // 59
    {"strict-transport-security", "max-age=31536000; includesubdomains; preload"},
    // 60
    {"vary", "accept-encoding"},
    // 61
    {"vary", "origin"},
    // 62
    {"x-content-type-options", "nosniff"},
    // 63
    {"x-xss-protection", "1; mode=block"},
    // 64
    {":status", "100"},
    // 65
    {":status", "204"},
    // 66
    {":status", "206"},
    // 67
    {":status", "302"},
    // 68
    {":status", "400"},
    // 69
    {":status", "403"},
    // 70
    {":status", "421"},
    // 71
    {":status", "425"},
    // 72
    {":status", "500"},
    // 73
    {"accept-language", ""},
    // 74
    {"access-control-allow-credentials", "FALSE"},
    // 75
    {"access-control-allow-credentials", "TRUE"},
    // 76
    {"access-control-allow-headers", "*"},
    // 77
    {"access-control-allow-methods", "get"},
    // 78
    {"access-control-allow-methods", "get, post, options"},
    // 79
    {"access-control-allow-methods", "options"},
    // 80
    {"access-control-expose-headers", "content-length"},
    // 81
    {"access-control-request-headers", "content-type"},
    // 82
    {"access-control-request-method", "get"},
    // 83
    {"access-control-request-method", "post"},
    // 84
    {"alt-svc", "clear"},
    // 85
    {"authorization", ""},
    // 86
    {"content-security-policy", "script-src 'none'; object-src 'none'; base-uri 'none'"},
    // 87
    {"early-data", "1"},
    // 88
    {"expect-ct", ""},
    // 89
    {"forwarded", ""},
    // 90
    {"if-range", ""},
    // 91
    {"origin", ""},
    // 92
    {"purpose", "prefetch"},
    // 93
    {"server", ""},
    // 94
    {"timing-allow-origin", "*"},
    // 95
    {"upgrade-insecure-requests", "1"},
    // 96
    {"user-agent", ""},
    // 97
    {"x-forwarded-for", ""},
    // 98
    {"x-frame-options", "deny"},
    // 99
    {"x-frame-options", "sameorigin"}
};

} // namespace quicsand
