[build]
# Standard-Optimierungen für alle Targets
rustflags = [
    "-C", "opt-level=3",
    "-C", "lto=thin",
    "-C", "codegen-units=1",
    "-C", "panic=abort",
    "-C", "embed-bitcode=yes",
    "-C", "target-cpu=native",
    "-C", "link-arg=-fuse-ld=lld",
]

# x86_64 spezifische Optimierungen
[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "target-feature=+aes,+ssse3,+sse4.1,+sse4.2,+avx,+avx2,+fma",
    "-C", "link-arg=-Wl,-O3",
]

# ARM64 spezifische Optimierungen
[target.aarch64-unknown-linux-gnu]
rustflags = [
    "-C", "target-feature=+aes,+sha2,+crc,+lse",
    "-C", "link-arg=-Wl,-O3",
]

# Profileinstellungen
[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
incremental = false

[profile.bench]
opt-level = 3
debug = false
lto = "thin"
codegen-units = 1

[profile.dev]
opt-level = 1

[profile.test]
opt-level = 1
