[package]
name = "quicfuscate_core"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1"
quiche = { path = "../../libs/quiche-patched/quiche", optional = true }

[features]
default = []
quiche = ["dep:quiche"]
