[package]
name = "qf-transport-path"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish = false

[features]
default = []
rust-tests = ["qf-common/rust-tests", "qf-transport-cc/rust-tests"]

[dependencies]
qf-common = { path = "../qf-common" }
qf-transport-cc = { path = "../qf-transport-cc" }
