[package]
name = "qf-hpke"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish = false

[features]
default = []
rust-tests = []

[dependencies]
hpke-rs = { version = "0.7", default-features = false, features = ["rustcrypto", "std", "hazmat"] }
hpke-rs-rust-crypto = { version = "0.7", features = ["std"] }
rustls = { version = "0.23", default-features = false, features = ["std", "logging"] }
