// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	qkeyParse: (qkeyData: string) => typedError<ParsedQKey, string>(__TAURI_INVOKE("qkey_parse", { qkeyData })),
	qkeyGenerate: (remote: string, sni: string, token: string | null, stealth: string | null, fec: string | null) => typedError<string, string>(__TAURI_INVOKE("qkey_generate", { remote, sni, token, stealth, fec })),
	engineConnect: (request: EngineConnectRequest_Deserialize) => typedError<null, string>(__TAURI_INVOKE("engine_connect", { request })),
	engineRotate: (tunnelId: string, qkeyData: string, sniOverride: string | null, circuit: PersistedCircuit_Deserialize, settings: unknown | null) => typedError<null, string>(__TAURI_INVOKE("engine_rotate", { tunnelId, qkeyData, sniOverride, circuit, settings })),
	engineDisconnect: () => typedError<null, string>(__TAURI_INVOKE("engine_disconnect")),
	engineStatus: () => typedError<EngineStatus, string>(__TAURI_INVOKE("engine_status")),
	engineStats: () => typedError<{
	latencyMs: number | null,
	lossPercent: number | null,
	bytesIn: number,
	bytesOut: number,
	packetsIn: number,
	packetsOut: number,
	uptimeSecs: number,
	fecMode: string,
	stealthMode: string,
	fecActivityPercent: number | null,
	fecRecoveredPackets: number,
	currentSni: string | null,
	circuitGeneration: number,
	circuitState: string,
	effectiveTunnelMtu: number,
	hops: CircuitHopStats[],
} | null, string>(__TAURI_INVOKE("engine_stats")),
	engineLogsSince: (cursor: number) => typedError<LogsResponse, string>(__TAURI_INVOKE("engine_logs_since", { cursor })),
	engineLogsClear: () => typedError<null, string>(__TAURI_INVOKE("engine_logs_clear")),
	saveState: (data: PersistedState_Deserialize) => typedError<null, string>(__TAURI_INVOKE("save_state", { data })),
	loadState: () => typedError<{
	schemaVersion: number,
	tunnels: PersistedTunnel_Serialize[],
	selectedTunnelId: string | null,
	settings: unknown,
} | null, string>(__TAURI_INVOKE("load_state")),
	detectCpuFeatures: () => typedError<string[], string>(__TAURI_INVOKE("detect_cpu_features")),
	clipboardReadText: () => typedError<string, string>(__TAURI_INVOKE("clipboard_read_text")),
	updaterRuntimeEnabled: () => typedError<boolean, string>(__TAURI_INVOKE("updater_runtime_enabled")),
};

/* Types */
/**  Defines the target browser for fingerprint spoofing. */
export type BrowserProfile = BrowserProfile_Serialize | BrowserProfile_Deserialize;

/**  Defines the target browser for fingerprint spoofing. */
export type BrowserProfile_Deserialize = 
/**  Google Chrome fingerprint (Chromium-based). */
"chrome" | 
/**  Google Chrome fingerprint (Chromium-based). */
"Chrome" | 
/**  Mozilla Firefox fingerprint. */
"firefox" | 
/**  Mozilla Firefox fingerprint. */
"Firefox" | 
/**  Apple Safari fingerprint. */
"safari" | 
/**  Apple Safari fingerprint. */
"Safari" | 
/**  Microsoft Edge fingerprint (Chromium-based with Edge-specific tweaks). */
"edge" | 
/**  Microsoft Edge fingerprint (Chromium-based with Edge-specific tweaks). */
"Edge";

/**  Defines the target browser for fingerprint spoofing. */
export type BrowserProfile_Serialize = 
/**  Google Chrome fingerprint (Chromium-based). */
"chrome" | 
/**  Mozilla Firefox fingerprint. */
"firefox" | 
/**  Apple Safari fingerprint. */
"safari" | 
/**  Microsoft Edge fingerprint (Chromium-based with Edge-specific tweaks). */
"edge";

export type BufferedLogLine = {
	seq: number,
	/**
	 *  Unix epoch milliseconds. Zero is meaningful only when `timestamp_valid`
	 *  is false and `timestamp_error` explains why wall-clock capture failed.
	 */
	tsMs: number,
	/**  Explicit validity metadata for the serialized `ts_ms` value. */
	timestampValid?: boolean,
	/**  Backend-owned diagnostic for an unavailable wall-clock timestamp. */
	timestampError?: string | null,
	level: string,
	message: string,
	target?: string | null,
};

/**  Operator-provided route-diversity constraints. */
export type CircuitDiversityPolicy = {
	/**  Require distinct provider labels for every hop. */
	provider?: boolean,
	/**  Require distinct region labels for every hop. */
	region?: boolean,
	/**  Require distinct jurisdiction labels for every hop. */
	jurisdiction?: boolean,
	/**  Require distinct failure-domain labels for every hop. */
	failure_domain?: boolean,
};

export type CircuitHopStats = {
	index: number,
	role: string,
	established: boolean,
	latencyMs: number | null,
	datagramBudget: number,
};

export type ConnectionStats = {
	latencyMs: number | null,
	lossPercent: number | null,
	bytesIn: number,
	bytesOut: number,
	packetsIn: number,
	packetsOut: number,
	uptimeSecs: number,
	fecMode: string,
	stealthMode: string,
	fecActivityPercent: number | null,
	fecRecoveredPackets: number,
	currentSni: string | null,
	circuitGeneration: number,
	circuitState: string,
	effectiveTunnelMtu: number,
	hops: CircuitHopStats[],
};

export type EngineConnectRequest = EngineConnectRequest_Serialize | EngineConnectRequest_Deserialize;

export type EngineConnectRequest_Deserialize = {
	tunnel_id: string,
	qkey_data: string,
	sni_override: string | null,
	circuit: PersistedCircuit_Deserialize | null,
	alternate_circuit: PersistedCircuit_Deserialize | null,
	settings: unknown,
};

export type EngineConnectRequest_Serialize = {
	tunnel_id: string,
	qkey_data: string,
	sni_override: string | null,
	circuit: PersistedCircuit_Serialize | null,
	alternate_circuit: PersistedCircuit_Serialize | null,
	settings: unknown,
};

export type EngineStatus = {
	state: string,
	activeTunnelId: string | null,
	lastError: string | null,
};

/**  FEC mode exposed by the engine configuration contract. */
export type FecMode = 
/**  FEC disabled entirely. */
"off" | 
/**  Adaptive FEC that selects a bounded runtime policy from measured loss. */
"auto";

/**  Browser and operating-system persona frozen for one hop generation. */
export type HopPersonaConfig = HopPersonaConfig_Serialize | HopPersonaConfig_Deserialize;

/**  Browser and operating-system persona frozen for one hop generation. */
export type HopPersonaConfig_Deserialize = {
	/**  Browser-shaped TLS, QUIC, and HTTP/3 profile. */
	browser: BrowserProfile_Deserialize,
	/**  Operating-system network fingerprint paired with the browser profile. */
	os: OsProfile_Deserialize,
};

/**  Browser and operating-system persona frozen for one hop generation. */
export type HopPersonaConfig_Serialize = {
	/**  Browser-shaped TLS, QUIC, and HTTP/3 profile. */
	browser: BrowserProfile_Serialize,
	/**  Operating-system network fingerprint paired with the browser profile. */
	os: OsProfile_Serialize,
};

/**  Function assigned to one authenticated circuit hop. */
export type HopRole = 
/**  Carries the next hop over an authenticated CONNECT-UDP association. */
"relay" | 
/**  Terminates the circuit through an authenticated CONNECT-IP tunnel. */
"exit";

export type LogsResponse = {
	cursor: number,
	lines: BufferedLogLine[],
};

/**  Defines the target operating system for fingerprint spoofing. */
export type OsProfile = OsProfile_Serialize | OsProfile_Deserialize;

/**  Defines the target operating system for fingerprint spoofing. */
export type OsProfile_Deserialize = 
/**  Microsoft Windows platform fingerprint. */
"windows" | 
/**  Microsoft Windows platform fingerprint. */
"Windows" | 
/**  Apple macOS platform fingerprint. */
"macos" | 
/**  Apple macOS platform fingerprint. */
"MacOS" | 
/**  Apple macOS platform fingerprint. */
"mac" | 
/**  Apple macOS platform fingerprint. */
"Mac" | 
/**  Linux desktop/server platform fingerprint. */
"linux" | 
/**  Linux desktop/server platform fingerprint. */
"Linux" | 
/**  Apple iOS mobile platform fingerprint. */
"ios" | 
/**  Apple iOS mobile platform fingerprint. */
"IOS" | 
/**  Apple iOS mobile platform fingerprint. */
"iOS" | 
/**  Google Android mobile platform fingerprint. */
"android" | 
/**  Google Android mobile platform fingerprint. */
"Android";

/**  Defines the target operating system for fingerprint spoofing. */
export type OsProfile_Serialize = 
/**  Microsoft Windows platform fingerprint. */
"windows" | 
/**  Apple macOS platform fingerprint. */
"macos" | 
/**  Linux desktop/server platform fingerprint. */
"linux" | 
/**  Apple iOS mobile platform fingerprint. */
"ios" | 
/**  Google Android mobile platform fingerprint. */
"android";

export type ParsedQKey = {
	qkeyId: string,
	remote: string,
	sni: string,
	hasToken: boolean,
	stealth: string | null,
	fec: string | null,
	extra: string | null,
};

export type PersistedCircuit = PersistedCircuit_Serialize | PersistedCircuit_Deserialize;

export type PersistedCircuitHop = PersistedCircuitHop_Serialize | PersistedCircuitHop_Deserialize;

export type PersistedCircuitHop_Deserialize = {
	id: string,
	label: string,
	remote: string,
	sni: string,
	qkeyId?: string,
	qkey: string,
	role: HopRole,
	provider?: string | null,
	region?: string | null,
	jurisdiction?: string | null,
	failureDomain?: string | null,
	verifyPeer?: boolean,
	caFile?: string,
	connectTimeoutMs?: number,
	idleTimeoutMs?: number,
	policy?: PersistedHopPolicy_Deserialize,
	hasToken?: boolean,
};

export type PersistedCircuitHop_Serialize = {
	id: string,
	label: string,
	remote: string,
	sni: string,
	qkeyId: string,
	qkey: string,
	role: HopRole,
	provider: string | null,
	region: string | null,
	jurisdiction: string | null,
	failureDomain: string | null,
	verifyPeer: boolean,
	caFile: string,
	connectTimeoutMs: number,
	idleTimeoutMs: number,
	policy: PersistedHopPolicy_Serialize,
	hasToken: boolean,
};

export type PersistedCircuit_Deserialize = {
	hops: PersistedCircuitHop_Deserialize[],
	maxHops?: number,
	maxParallelCircuits?: number,
	allowSingleHopFallback?: boolean,
	diversity?: CircuitDiversityPolicy,
};

export type PersistedCircuit_Serialize = {
	hops: PersistedCircuitHop_Serialize[],
	maxHops: number,
	maxParallelCircuits: number,
	allowSingleHopFallback: boolean,
	diversity: CircuitDiversityPolicy,
};

export type PersistedHopPolicy = PersistedHopPolicy_Serialize | PersistedHopPolicy_Deserialize;

export type PersistedHopPolicy_Deserialize = {
	persona?: HopPersonaConfig_Deserialize | null,
	fecMode?: FecMode | null,
	enableTrafficPadding?: boolean | null,
	enableTimingObfuscation?: boolean | null,
	enableCoverPing?: boolean | null,
};

export type PersistedHopPolicy_Serialize = {
	persona: HopPersonaConfig_Serialize | null,
	fecMode: FecMode | null,
	enableTrafficPadding: boolean | null,
	enableTimingObfuscation: boolean | null,
	enableCoverPing: boolean | null,
};

export type PersistedState = PersistedState_Serialize | PersistedState_Deserialize;

export type PersistedState_Deserialize = {
	schemaVersion: number,
	tunnels: PersistedTunnel_Deserialize[],
	selectedTunnelId: string | null,
	settings: unknown,
};

export type PersistedState_Serialize = {
	schemaVersion: number,
	tunnels: PersistedTunnel_Serialize[],
	selectedTunnelId: string | null,
	settings: unknown,
};

export type PersistedTunnel = PersistedTunnel_Serialize | PersistedTunnel_Deserialize;

export type PersistedTunnel_Deserialize = {
	id: string,
	name: string,
	remote: string,
	sni: string,
	qkey: string,
	/**
	 *  Unix epoch milliseconds. Zero is a legacy disk sentinel repaired by
	 *  `sanitize_persisted_state()` before this value reaches the frontend.
	 */
	createdAt: number,
	countryCode?: string | null,
	location?: string | null,
	hasToken?: boolean,
	debugSniOverride?: string | null,
	circuit?: PersistedCircuit_Deserialize | null,
	alternateCircuit?: PersistedCircuit_Deserialize | null,
};

export type PersistedTunnel_Serialize = {
	id: string,
	name: string,
	remote: string,
	sni: string,
	qkey: string,
	/**
	 *  Unix epoch milliseconds. Zero is a legacy disk sentinel repaired by
	 *  `sanitize_persisted_state()` before this value reaches the frontend.
	 */
	createdAt: number,
	countryCode: string | null,
	location: string | null,
	hasToken: boolean,
	debugSniOverride: string | null,
	circuit: PersistedCircuit_Serialize | null,
	alternateCircuit: PersistedCircuit_Serialize | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

