name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build quiche
        run: |
          cd libs/quiche-patched
          cargo build --release
      - name: Build Rust workspace
        run: |
          cargo build --manifest-path rust/Cargo.toml --workspace --release
      - name: Test Rust workspace
        run: |
          cargo test --manifest-path rust/Cargo.toml --workspace --all-targets
      - name: Run integration tests
        run: |
          cargo test --manifest-path rust/tests/Cargo.toml
      - name: Configure
        run: |
          mkdir build && cd build
          cmake ..
      - name: Build
        run: |
          cd build
          cmake --build .
      - name: Test
        run: |
          cd build
          ctest --output-on-failure
